// MathBookData.ts — 80 mathematical theorems/formulas for the Book of Math
//
// Sources: ProofWiki (CC BY-SA 3.0), DLMF (public domain), OpenStax (CC BY 4.0),
// Wikipedia (CC BY-SA 4.0). All formulas are standard mathematical results in
// the public domain.

export interface MathFormula {
    id: number;
    chapter: string;
    name: string;
    latex: string;
    keywords?: string[];
}

export const MATH_FORMULAS: MathFormula[] = [
    // ═══════════════════════════════════════════════════════════
    // Chapter 1: Geometry (1-20)
    // ═══════════════════════════════════════════════════════════
    { id: 1,  chapter: 'Geometry', name: 'Pythagorean Theorem',
      latex: 'a^2 + b^2 = c^2',
      keywords: ['right triangle', 'hypotenuse', 'legs', 'pythag'] },
    { id: 2,  chapter: 'Geometry', name: 'Law of Cosines',
      latex: 'c^2 = a^2 + b^2 - 2ab\\cos C',
      keywords: ['triangle', 'trig', 'cosine', 'sas'] },
    { id: 3,  chapter: 'Geometry', name: 'Law of Sines',
      latex: '\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}',
      keywords: ['triangle', 'trig', 'sine', 'asa'] },
    { id: 4,  chapter: 'Geometry', name: 'Area of Triangle',
      latex: 'A = \\frac{1}{2}bh',
      keywords: ['triangle', 'area', 'base', 'height'] },
    { id: 5,  chapter: 'Geometry', name: 'Area of Circle',
      latex: 'A = \\pi r^2',
      keywords: ['circle', 'area', 'pi', 'radius'] },
    { id: 6,  chapter: 'Geometry', name: 'Circumference',
      latex: 'C = 2\\pi r',
      keywords: ['circle', 'perimeter', 'pi', 'radius'] },
    { id: 7,  chapter: 'Geometry', name: 'Surface Area of Sphere',
      latex: 'S = 4\\pi r^2',
      keywords: ['sphere', 'area', 'surface', 'pi'] },
    { id: 8,  chapter: 'Geometry', name: 'Volume of Sphere',
      latex: 'V = \\frac{4}{3}\\pi r^3',
      keywords: ['sphere', 'volume', 'pi', 'radius'] },
    { id: 9,  chapter: 'Geometry', name: 'Volume of Cylinder',
      latex: 'V = \\pi r^2 h',
      keywords: ['cylinder', 'volume', 'pi', 'height'] },
    { id: 10, chapter: 'Geometry', name: 'Distance Formula',
      latex: 'd = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}',
      keywords: ['distance', 'coordinates', 'points', 'plane'] },
    { id: 11, chapter: 'Geometry', name: 'Midpoint Formula',
      latex: 'M = \\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)',
      keywords: ['midpoint', 'segment', 'coordinates'] },
    { id: 12, chapter: 'Geometry', name: 'Slope Formula',
      latex: 'm = \\frac{y_2 - y_1}{x_2 - x_1}',
      keywords: ['slope', 'line', 'rise', 'run', 'gradient'] },
    { id: 13, chapter: 'Geometry', name: "Heron's Formula",
      latex: 'A = \\sqrt{s(s-a)(s-b)(s-c)}',
      keywords: ['triangle', 'area', 'sides', 'semiperimeter', 'heron'] },
    { id: 14, chapter: 'Geometry', name: 'Circle Equation',
      latex: '(x-h)^2 + (y-k)^2 = r^2',
      keywords: ['circle', 'equation', 'center', 'radius'] },
    { id: 15, chapter: 'Geometry', name: 'Ellipse Equation',
      latex: '\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1',
      keywords: ['ellipse', 'conic', 'axes'] },
    { id: 16, chapter: 'Geometry', name: 'Arc Length',
      latex: 's = r\\theta',
      keywords: ['arc', 'circle', 'radian', 'angle'] },
    { id: 17, chapter: 'Geometry', name: 'Sector Area',
      latex: 'A = \\frac{1}{2}r^2\\theta',
      keywords: ['sector', 'circle', 'area', 'angle'] },
    { id: 18, chapter: 'Geometry', name: "Euler's Polyhedron Formula",
      latex: 'V - E + F = 2',
      keywords: ['euler', 'polyhedron', 'vertices', 'edges', 'faces', 'topology'] },
    { id: 19, chapter: 'Geometry', name: 'Angle Sum of Triangle',
      latex: '\\alpha + \\beta + \\gamma = \\pi',
      keywords: ['triangle', 'angles', 'sum', 'pi'] },
    { id: 20, chapter: 'Geometry', name: 'Exterior Angle Theorem',
      latex: '\\theta_{ext} = \\alpha + \\beta',
      keywords: ['triangle', 'exterior', 'angle'] },

    // ═══════════════════════════════════════════════════════════
    // Chapter 2: Algebra (21-40)
    // ═══════════════════════════════════════════════════════════
    { id: 21, chapter: 'Algebra', name: 'Quadratic Formula',
      latex: 'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}',
      keywords: ['quadratic', 'roots', 'discriminant', 'polynomial'] },
    { id: 22, chapter: 'Algebra', name: 'Difference of Squares',
      latex: 'a^2 - b^2 = (a+b)(a-b)',
      keywords: ['factoring', 'identity', 'polynomial'] },
    { id: 23, chapter: 'Algebra', name: 'Perfect Square Trinomial',
      latex: '(a+b)^2 = a^2 + 2ab + b^2',
      keywords: ['expansion', 'identity', 'polynomial', 'binomial'] },
    { id: 24, chapter: 'Algebra', name: 'Difference of Cubes',
      latex: 'a^3 - b^3 = (a-b)(a^2+ab+b^2)',
      keywords: ['factoring', 'identity', 'cubic', 'polynomial'] },
    { id: 25, chapter: 'Algebra', name: 'Geometric Series Sum',
      latex: 'S_n = \\frac{a(1-r^n)}{1-r}',
      keywords: ['series', 'geometric', 'sum', 'finite'] },
    { id: 26, chapter: 'Algebra', name: 'Infinite Geometric Series',
      latex: 'S = \\frac{a}{1-r}',
      keywords: ['series', 'geometric', 'infinite', 'convergent'] },
    { id: 27, chapter: 'Algebra', name: 'Arithmetic Series',
      latex: 'S_n = \\frac{n(a_1 + a_n)}{2}',
      keywords: ['series', 'arithmetic', 'sum', 'sequence'] },
    { id: 28, chapter: 'Algebra', name: "Euler's Identity",
      latex: 'e^{i\\pi} + 1 = 0',
      keywords: ['euler', 'identity', 'complex', 'exponential'] },
    { id: 29, chapter: 'Algebra', name: 'Logarithm Product Rule',
      latex: '\\log(ab) = \\log a + \\log b',
      keywords: ['log', 'logarithm', 'product'] },
    { id: 30, chapter: 'Algebra', name: 'Change of Base',
      latex: '\\log_b x = \\frac{\\ln x}{\\ln b}',
      keywords: ['log', 'logarithm', 'base', 'natural log'] },
    { id: 31, chapter: 'Algebra', name: 'Exponent Product Rule',
      latex: 'a^m \\cdot a^n = a^{m+n}',
      keywords: ['exponent', 'power', 'product'] },
    { id: 32, chapter: 'Algebra', name: 'Power of a Power',
      latex: '(a^m)^n = a^{mn}',
      keywords: ['exponent', 'power', 'identity'] },
    { id: 33, chapter: 'Algebra', name: 'AM-GM Inequality',
      latex: '\\frac{a+b}{2} \\geq \\sqrt{ab}',
      keywords: ['inequality', 'mean', 'arithmetic', 'geometric'] },
    { id: 34, chapter: 'Algebra', name: 'Triangle Inequality',
      latex: '|a+b| \\leq |a| + |b|',
      keywords: ['inequality', 'absolute value', 'triangle'] },
    { id: 35, chapter: 'Algebra', name: 'Absolute Value',
      latex: '|x| = \\sqrt{x^2}',
      keywords: ['absolute value', 'magnitude', 'modulus'] },
    { id: 36, chapter: 'Algebra', name: 'Compound Interest',
      latex: 'A = P\\left(1 + \\frac{r}{n}\\right)^{nt}',
      keywords: ['finance', 'interest', 'principal', 'compound'] },
    { id: 37, chapter: 'Algebra', name: 'Permutations',
      latex: 'P(n,r) = \\frac{n!}{(n-r)!}',
      keywords: ['combinatorics', 'permutation', 'factorial', 'arrange'] },
    { id: 38, chapter: 'Algebra', name: 'Combinations',
      latex: '\\binom{n}{r} = \\frac{n!}{r!(n-r)!}',
      keywords: ['combinatorics', 'combination', 'binomial', 'choose', 'factorial'] },
    { id: 39, chapter: 'Algebra', name: 'Fibonacci Recurrence',
      latex: 'F_n = F_{n-1} + F_{n-2}',
      keywords: ['fibonacci', 'sequence', 'recurrence'] },
    { id: 40, chapter: 'Algebra', name: "De Moivre's Theorem",
      latex: '(\\cos\\theta + i\\sin\\theta)^n = \\cos n\\theta + i\\sin n\\theta',
      keywords: ['complex', 'trig', 'demoivre', 'powers'] },

    // ═══════════════════════════════════════════════════════════
    // Chapter 3: Calculus (41-60)
    // ═══════════════════════════════════════════════════════════
    { id: 41, chapter: 'Calculus', name: 'Power Rule',
      latex: '\\frac{d}{dx}x^n = nx^{n-1}',
      keywords: ['derivative', 'power', 'differentiation'] },
    { id: 42, chapter: 'Calculus', name: 'Chain Rule',
      latex: '\\frac{d}{dx}f(g(x)) = f\'(g(x)) \\cdot g\'(x)',
      keywords: ['derivative', 'chain', 'composition'] },
    { id: 43, chapter: 'Calculus', name: 'Product Rule',
      latex: '(fg)\' = f\'g + fg\'',
      keywords: ['derivative', 'product', 'differentiation'] },
    { id: 44, chapter: 'Calculus', name: 'Quotient Rule',
      latex: '\\left(\\frac{f}{g}\\right)\' = \\frac{f\'g - fg\'}{g^2}',
      keywords: ['derivative', 'quotient', 'differentiation'] },
    { id: 45, chapter: 'Calculus', name: 'Fundamental Theorem of Calculus',
      latex: '\\int_a^b f(x)\\,dx = F(b) - F(a)',
      keywords: ['integral', 'fundamental', 'antiderivative'] },
    { id: 46, chapter: 'Calculus', name: 'Integration by Parts',
      latex: '\\int u\\,dv = uv - \\int v\\,du',
      keywords: ['integral', 'integration', 'parts'] },
    { id: 47, chapter: 'Calculus', name: 'Taylor Series',
      latex: 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n',
      keywords: ['series', 'taylor', 'expansion', 'approximation'] },
    { id: 48, chapter: 'Calculus', name: "Euler's Formula",
      latex: 'e^{ix} = \\cos x + i\\sin x',
      keywords: ['euler', 'complex', 'exponential', 'trig'] },
    { id: 49, chapter: 'Calculus', name: 'Derivative of sin',
      latex: '\\frac{d}{dx}\\sin x = \\cos x',
      keywords: ['derivative', 'sine', 'trig'] },
    { id: 50, chapter: 'Calculus', name: 'Derivative of cos',
      latex: '\\frac{d}{dx}\\cos x = -\\sin x',
      keywords: ['derivative', 'cosine', 'trig'] },
    { id: 51, chapter: 'Calculus', name: 'Derivative of e^x',
      latex: '\\frac{d}{dx}e^x = e^x',
      keywords: ['derivative', 'exponential', 'natural'] },
    { id: 52, chapter: 'Calculus', name: 'Derivative of ln',
      latex: '\\frac{d}{dx}\\ln x = \\frac{1}{x}',
      keywords: ['derivative', 'log', 'logarithm', 'natural'] },
    { id: 53, chapter: 'Calculus', name: "L'Hopital's Rule",
      latex: '\\lim_{x \\to a}\\frac{f(x)}{g(x)} = \\lim_{x \\to a}\\frac{f\'(x)}{g\'(x)}',
      keywords: ['limit', 'lhopital', 'indeterminate'] },
    { id: 54, chapter: 'Calculus', name: 'Mean Value Theorem',
      latex: 'f\'(c) = \\frac{f(b)-f(a)}{b-a}',
      keywords: ['derivative', 'mean value', 'mvt'] },
    { id: 55, chapter: 'Calculus', name: 'Gaussian Integral',
      latex: '\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}',
      keywords: ['integral', 'gaussian', 'exponential', 'pi'] },
    { id: 56, chapter: 'Calculus', name: 'Lorentz Factor',
      latex: '\\gamma = \\frac{1}{\\sqrt{1-\\frac{v^2}{c^2}}}',
      keywords: ['relativity', 'lorentz', 'physics', 'velocity'] },
    { id: 57, chapter: 'Calculus', name: 'Wave Equation',
      latex: '\\frac{\\partial^2 u}{\\partial t^2} = c^2 \\frac{\\partial^2 u}{\\partial x^2}',
      keywords: ['pde', 'wave', 'physics', 'partial derivative'] },
    { id: 58, chapter: 'Calculus', name: 'Heat Equation',
      latex: '\\frac{\\partial u}{\\partial t} = k \\frac{\\partial^2 u}{\\partial x^2}',
      keywords: ['pde', 'heat', 'diffusion', 'partial derivative'] },
    { id: 59, chapter: 'Calculus', name: 'Laplacian',
      latex: '\\nabla^2 f = \\frac{\\partial^2 f}{\\partial x^2} + \\frac{\\partial^2 f}{\\partial y^2}',
      keywords: ['laplacian', 'pde', 'partial derivative', 'nabla'] },
    { id: 60, chapter: 'Calculus', name: 'Schrodinger Equation',
      latex: 'i\\hbar\\frac{\\partial}{\\partial t}\\Psi = \\hat{H}\\Psi',
      keywords: ['quantum', 'schrodinger', 'physics', 'wave function'] },

    // ═══════════════════════════════════════════════════════════
    // Chapter 4: Linear Algebra (61-80)
    // Sources: ProofWiki, OpenStax Linear Algebra, Wikipedia (CC BY-SA 4.0)
    //
    // Note: matrix-shaped formulas (pmatrix/bmatrix) are not yet supported
    // by MatematexBridge. Determinant 2x2 (#66) uses an entry-form (a_{11}a_{22})
    // until the bridge gains mtable handling in Phase 6.6.
    // ═══════════════════════════════════════════════════════════
    { id: 61, chapter: 'Linear Algebra', name: 'Matrix Multiplication',
      latex: '(AB)_{ij} = \\sum_{k=1}^{n} a_{ik} b_{kj}',
      keywords: ['matrix', 'product', 'multiplication'] },
    { id: 62, chapter: 'Linear Algebra', name: 'Identity Matrix',
      latex: 'I_n = \\mathrm{diag}(1, 1, \\ldots, 1)',
      keywords: ['matrix', 'identity', 'diagonal'] },
    { id: 63, chapter: 'Linear Algebra', name: 'Matrix Inverse',
      latex: 'A A^{-1} = A^{-1} A = I',
      keywords: ['matrix', 'inverse', 'identity'] },
    { id: 64, chapter: 'Linear Algebra', name: 'Transpose',
      latex: '(A^T)_{ij} = A_{ji}',
      keywords: ['matrix', 'transpose'] },
    { id: 65, chapter: 'Linear Algebra', name: 'Transpose of Product',
      latex: '(AB)^T = B^T A^T',
      keywords: ['matrix', 'transpose', 'product', 'identity'] },
    { id: 66, chapter: 'Linear Algebra', name: 'Determinant of 2x2',
      latex: '\\det A = a_{11} a_{22} - a_{12} a_{21}',
      keywords: ['matrix', 'determinant', '2x2'] },
    { id: 67, chapter: 'Linear Algebra', name: 'Determinant of Product',
      latex: '\\det(AB) = \\det(A)\\,\\det(B)',
      keywords: ['matrix', 'determinant', 'product', 'identity'] },
    { id: 68, chapter: 'Linear Algebra', name: 'Cofactor Expansion',
      latex: '\\det A = \\sum_{j=1}^{n} (-1)^{i+j} a_{ij} M_{ij}',
      keywords: ['matrix', 'determinant', 'cofactor', 'minor', 'laplace'] },
    { id: 69, chapter: 'Linear Algebra', name: 'Eigenvalue Equation',
      latex: 'A \\mathbf{v} = \\lambda \\mathbf{v}',
      keywords: ['matrix', 'eigenvalue', 'eigenvector', 'lambda'] },
    { id: 70, chapter: 'Linear Algebra', name: 'Characteristic Polynomial',
      latex: '\\det(A - \\lambda I) = 0',
      keywords: ['matrix', 'eigenvalue', 'characteristic', 'polynomial'] },
    { id: 71, chapter: 'Linear Algebra', name: 'Trace',
      latex: '\\mathrm{tr}(A) = \\sum_{i=1}^{n} a_{ii}',
      keywords: ['matrix', 'trace', 'diagonal'] },
    { id: 72, chapter: 'Linear Algebra', name: 'Trace of Product',
      latex: '\\mathrm{tr}(AB) = \\mathrm{tr}(BA)',
      keywords: ['matrix', 'trace', 'product', 'identity', 'cyclic'] },
    { id: 73, chapter: 'Linear Algebra', name: 'Dot Product',
      latex: '\\mathbf{a} \\cdot \\mathbf{b} = \\sum_{i=1}^{n} a_i b_i',
      keywords: ['vector', 'dot product', 'inner product'] },
    { id: 74, chapter: 'Linear Algebra', name: 'Cross Product Magnitude',
      latex: '\\lVert \\mathbf{a} \\times \\mathbf{b} \\rVert = \\lVert \\mathbf{a} \\rVert \\lVert \\mathbf{b} \\rVert \\sin\\theta',
      keywords: ['vector', 'cross product', 'norm', 'angle'] },
    { id: 75, chapter: 'Linear Algebra', name: 'Cauchy-Schwarz Inequality',
      latex: '\\lvert \\langle u, v \\rangle \\rvert \\leq \\lVert u \\rVert \\, \\lVert v \\rVert',
      keywords: ['inequality', 'inner product', 'cauchy', 'schwarz', 'norm'] },
    { id: 76, chapter: 'Linear Algebra', name: 'Vector Norm (L2)',
      latex: '\\lVert \\mathbf{x} \\rVert_2 = \\sqrt{\\sum_{i=1}^{n} x_i^2}',
      keywords: ['vector', 'norm', 'magnitude', 'euclidean', 'l2'] },
    { id: 77, chapter: 'Linear Algebra', name: 'Orthogonality',
      latex: '\\mathbf{u} \\cdot \\mathbf{v} = 0',
      keywords: ['vector', 'orthogonal', 'perpendicular', 'dot product'] },
    { id: 78, chapter: 'Linear Algebra', name: 'Rank-Nullity Theorem',
      latex: '\\dim(\\ker T) + \\dim(\\mathrm{im}\\,T) = \\dim V',
      keywords: ['linear map', 'rank', 'nullity', 'kernel', 'image'] },
    { id: 79, chapter: 'Linear Algebra', name: 'Spectral Decomposition',
      latex: 'A = Q \\Lambda Q^T',
      keywords: ['matrix', 'spectral', 'diagonalization', 'symmetric', 'eigenvalue'] },
    { id: 80, chapter: 'Linear Algebra', name: 'Singular Value Decomposition',
      latex: 'A = U \\Sigma V^T',
      keywords: ['matrix', 'svd', 'decomposition', 'singular value'] },
];
