// MathBookData.ts — 60 mathematical theorems/formulas for the Book of Math
//
// Sources: ProofWiki (CC BY-SA 3.0), DLMF (public domain), OpenStax (CC BY 4.0)
// All formulas are standard mathematical results in the public domain.

export interface MathFormula {
    id: number;
    chapter: string;
    name: string;
    latex: string;
}

export const MATH_FORMULAS: MathFormula[] = [
    // ═══════════════════════════════════════════════════════════
    // Chapter 1: Geometry (1-20)
    // ═══════════════════════════════════════════════════════════
    { id: 1,  chapter: 'Geometry', name: 'Pythagorean Theorem',
      latex: 'a^2 + b^2 = c^2' },
    { id: 2,  chapter: 'Geometry', name: 'Law of Cosines',
      latex: 'c^2 = a^2 + b^2 - 2ab\\cos C' },
    { id: 3,  chapter: 'Geometry', name: 'Law of Sines',
      latex: '\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}' },
    { id: 4,  chapter: 'Geometry', name: 'Area of Triangle',
      latex: 'A = \\frac{1}{2}bh' },
    { id: 5,  chapter: 'Geometry', name: 'Area of Circle',
      latex: 'A = \\pi r^2' },
    { id: 6,  chapter: 'Geometry', name: 'Circumference',
      latex: 'C = 2\\pi r' },
    { id: 7,  chapter: 'Geometry', name: 'Surface Area of Sphere',
      latex: 'S = 4\\pi r^2' },
    { id: 8,  chapter: 'Geometry', name: 'Volume of Sphere',
      latex: 'V = \\frac{4}{3}\\pi r^3' },
    { id: 9,  chapter: 'Geometry', name: 'Volume of Cylinder',
      latex: 'V = \\pi r^2 h' },
    { id: 10, chapter: 'Geometry', name: 'Distance Formula',
      latex: 'd = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}' },
    { id: 11, chapter: 'Geometry', name: 'Midpoint Formula',
      latex: 'M = \\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)' },
    { id: 12, chapter: 'Geometry', name: 'Slope Formula',
      latex: 'm = \\frac{y_2 - y_1}{x_2 - x_1}' },
    { id: 13, chapter: 'Geometry', name: "Heron's Formula",
      latex: 'A = \\sqrt{s(s-a)(s-b)(s-c)}' },
    { id: 14, chapter: 'Geometry', name: 'Circle Equation',
      latex: '(x-h)^2 + (y-k)^2 = r^2' },
    { id: 15, chapter: 'Geometry', name: 'Ellipse Equation',
      latex: '\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1' },
    { id: 16, chapter: 'Geometry', name: 'Arc Length',
      latex: 's = r\\theta' },
    { id: 17, chapter: 'Geometry', name: 'Sector Area',
      latex: 'A = \\frac{1}{2}r^2\\theta' },
    { id: 18, chapter: 'Geometry', name: "Euler's Polyhedron Formula",
      latex: 'V - E + F = 2' },
    { id: 19, chapter: 'Geometry', name: 'Angle Sum of Triangle',
      latex: '\\alpha + \\beta + \\gamma = \\pi' },
    { id: 20, chapter: 'Geometry', name: 'Exterior Angle Theorem',
      latex: '\\theta_{ext} = \\alpha + \\beta' },

    // ═══════════════════════════════════════════════════════════
    // Chapter 2: Algebra (21-40)
    // ═══════════════════════════════════════════════════════════
    { id: 21, chapter: 'Algebra', name: 'Quadratic Formula',
      latex: 'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}' },
    { id: 22, chapter: 'Algebra', name: 'Difference of Squares',
      latex: 'a^2 - b^2 = (a+b)(a-b)' },
    { id: 23, chapter: 'Algebra', name: 'Perfect Square Trinomial',
      latex: '(a+b)^2 = a^2 + 2ab + b^2' },
    { id: 24, chapter: 'Algebra', name: 'Difference of Cubes',
      latex: 'a^3 - b^3 = (a-b)(a^2+ab+b^2)' },
    { id: 25, chapter: 'Algebra', name: 'Geometric Series Sum',
      latex: 'S_n = \\frac{a(1-r^n)}{1-r}' },
    { id: 26, chapter: 'Algebra', name: 'Infinite Geometric Series',
      latex: 'S = \\frac{a}{1-r}' },
    { id: 27, chapter: 'Algebra', name: 'Arithmetic Series',
      latex: 'S_n = \\frac{n(a_1 + a_n)}{2}' },
    { id: 28, chapter: 'Algebra', name: "Euler's Identity",
      latex: 'e^{i\\pi} + 1 = 0' },
    { id: 29, chapter: 'Algebra', name: 'Logarithm Product Rule',
      latex: '\\log(ab) = \\log a + \\log b' },
    { id: 30, chapter: 'Algebra', name: 'Change of Base',
      latex: '\\log_b x = \\frac{\\ln x}{\\ln b}' },
    { id: 31, chapter: 'Algebra', name: 'Exponent Product Rule',
      latex: 'a^m \\cdot a^n = a^{m+n}' },
    { id: 32, chapter: 'Algebra', name: 'Power of a Power',
      latex: '(a^m)^n = a^{mn}' },
    { id: 33, chapter: 'Algebra', name: 'AM-GM Inequality',
      latex: '\\frac{a+b}{2} \\geq \\sqrt{ab}' },
    { id: 34, chapter: 'Algebra', name: 'Triangle Inequality',
      latex: '|a+b| \\leq |a| + |b|' },
    { id: 35, chapter: 'Algebra', name: 'Absolute Value',
      latex: '|x| = \\sqrt{x^2}' },
    { id: 36, chapter: 'Algebra', name: 'Compound Interest',
      latex: 'A = P\\left(1 + \\frac{r}{n}\\right)^{nt}' },
    { id: 37, chapter: 'Algebra', name: 'Permutations',
      latex: 'P(n,r) = \\frac{n!}{(n-r)!}' },
    { id: 38, chapter: 'Algebra', name: 'Combinations',
      latex: '\\binom{n}{r} = \\frac{n!}{r!(n-r)!}' },
    { id: 39, chapter: 'Algebra', name: 'Fibonacci Recurrence',
      latex: 'F_n = F_{n-1} + F_{n-2}' },
    { id: 40, chapter: 'Algebra', name: "De Moivre's Theorem",
      latex: '(\\cos\\theta + i\\sin\\theta)^n = \\cos n\\theta + i\\sin n\\theta' },

    // ═══════════════════════════════════════════════════════════
    // Chapter 3: Calculus (41-60)
    // ═══════════════════════════════════════════════════════════
    { id: 41, chapter: 'Calculus', name: 'Power Rule',
      latex: '\\frac{d}{dx}x^n = nx^{n-1}' },
    { id: 42, chapter: 'Calculus', name: 'Chain Rule',
      latex: '\\frac{d}{dx}f(g(x)) = f\'(g(x)) \\cdot g\'(x)' },
    { id: 43, chapter: 'Calculus', name: 'Product Rule',
      latex: '(fg)\' = f\'g + fg\'' },
    { id: 44, chapter: 'Calculus', name: 'Quotient Rule',
      latex: '\\left(\\frac{f}{g}\\right)\' = \\frac{f\'g - fg\'}{g^2}' },
    { id: 45, chapter: 'Calculus', name: 'Fundamental Theorem of Calculus',
      latex: '\\int_a^b f(x)\\,dx = F(b) - F(a)' },
    { id: 46, chapter: 'Calculus', name: 'Integration by Parts',
      latex: '\\int u\\,dv = uv - \\int v\\,du' },
    { id: 47, chapter: 'Calculus', name: 'Taylor Series',
      latex: 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n' },
    { id: 48, chapter: 'Calculus', name: "Euler's Formula",
      latex: 'e^{ix} = \\cos x + i\\sin x' },
    { id: 49, chapter: 'Calculus', name: 'Derivative of sin',
      latex: '\\frac{d}{dx}\\sin x = \\cos x' },
    { id: 50, chapter: 'Calculus', name: 'Derivative of cos',
      latex: '\\frac{d}{dx}\\cos x = -\\sin x' },
    { id: 51, chapter: 'Calculus', name: 'Derivative of e^x',
      latex: '\\frac{d}{dx}e^x = e^x' },
    { id: 52, chapter: 'Calculus', name: 'Derivative of ln',
      latex: '\\frac{d}{dx}\\ln x = \\frac{1}{x}' },
    { id: 53, chapter: 'Calculus', name: "L'Hopital's Rule",
      latex: '\\lim_{x \\to a}\\frac{f(x)}{g(x)} = \\lim_{x \\to a}\\frac{f\'(x)}{g\'(x)}' },
    { id: 54, chapter: 'Calculus', name: 'Mean Value Theorem',
      latex: 'f\'(c) = \\frac{f(b)-f(a)}{b-a}' },
    { id: 55, chapter: 'Calculus', name: 'Gaussian Integral',
      latex: '\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}' },
    { id: 56, chapter: 'Calculus', name: 'Lorentz Factor',
      latex: '\\gamma = \\frac{1}{\\sqrt{1-\\frac{v^2}{c^2}}}' },
    { id: 57, chapter: 'Calculus', name: 'Wave Equation',
      latex: '\\frac{\\partial^2 u}{\\partial t^2} = c^2 \\frac{\\partial^2 u}{\\partial x^2}' },
    { id: 58, chapter: 'Calculus', name: 'Heat Equation',
      latex: '\\frac{\\partial u}{\\partial t} = k \\frac{\\partial^2 u}{\\partial x^2}' },
    { id: 59, chapter: 'Calculus', name: 'Laplacian',
      latex: '\\nabla^2 f = \\frac{\\partial^2 f}{\\partial x^2} + \\frac{\\partial^2 f}{\\partial y^2}' },
    { id: 60, chapter: 'Calculus', name: 'Schrodinger Equation',
      latex: 'i\\hbar\\frac{\\partial}{\\partial t}\\Psi = \\hat{H}\\Psi' },
];
